### ISSUE TITLE
[FR] Seting sys.path for hy so it can locate modules correctly.

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#458]
As title. 
I think that requires a lot of work because python have a lot of different build tool.

**Comment by glyh** [comment]
So for example, this is a `pyproject.toml`, a `project.clj` equivalent for python, we have to read tool.setuptools.packages.find.where section to locate our source file:
```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "chibicc-hy"
version = "0.0.1"
dependencies = [
    "hy == 1.0a4",
    "hyrule == 0.1"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
chibicc_hy = ["*.hy"]

[tool.setuptools]
zip-safe = false

```
